num1 = input("First number: ")
num2 = input("second number: ")
sum = int(num1) + int(num2)
print(sum)
num1 = input("First number: ")
num2 = input("second number: ")
result = int(num1) - int(num2)
print(result)
num1 = input("First number: ")
num2 = input("second number: ")
result = int(num1) * int(num2)
print(result)
num1 = input("First number: ")
num2 = input("second number: ")
result = int(num1) / int(num2)
print(result)